events {}

http {

  # Tier-1 local rate limiting
  limit_req_zone $binary_remote_addr zone=ip_limit:10m rate=5r/s;

  upstream gate_service {
    server 127.0.0.1:8001;
  }

  upstream app_service {
    server 127.0.0.1:8080;
  }

  server {
    listen 9000;

    # Internal call to gate
    location = /_gate {
      internal;
      proxy_pass http://gate_service/buy;
    }

    # Public endpoint
    location /buy {

      # Tier 1: cheap local reject (no Python)
      limit_req zone=ip_limit burst=1 nodelay;

      # Tier 2: global correctness (Python + Redis)
      auth_request /_gate;

      # Any failure → deny
      error_page 401 403 429 503 = @deny;

      # Allowed requests go to app
      proxy_pass http://app_service;
    }

    # Deny handler
    location @deny {
      return 429;
    }
  }
}
